export const mockEns = [
  {
    id: 'EN-1021',
    desc: 'Validação do fluxo de contratação digital',
    status: 'Finalizado',
    squad: 'Core Fibra',
    project: 'Portal Comercial B2C',
    owner: 'Marcelo',
    week: 'S1',
    bug: 'BUG-342',
  },
  {
    id: 'EN-1022',
    desc: 'Teste de autenticação com múltiplos perfis',
    status: 'Bloqueado',
    squad: 'Core Fibra',
    project: 'Portal Comercial B2C',
    owner: 'Marcelo',
    week: 'S2',
    bug: '—',
  },
  {
    id: 'EN-1023',
    desc: 'Validação de jornada de upgrade de plano',
    status: 'Impactado',
    squad: 'B2B Digital',
    project: 'Upgrade Jornada',
    owner: 'Marcelo',
    week: 'S3',
    bug: 'BUG-355',
  },
  {
    id: 'EN-1023A',
    desc: 'Acompanhamento da jornada de instalação técnica',
    status: 'Em andamento',
    squad: 'Core Fibra',
    project: 'Portal Comercial B2C',
    owner: 'Marcelo',
    week: 'S3',
    bug: '—',
  },
  {
    id: 'EN-1024',
    desc: 'Cobertura do fluxo de cancelamento',
    status: 'Pendente',
    squad: 'Core Fibra',
    project: 'Portal Comercial B2C',
    owner: 'Marcelo',
    week: 'S4',
    bug: '—',
  },
  {
    id: 'EN-1025',
    desc: 'Teste E2E do onboarding residencial',
    status: 'Finalizado',
    squad: 'CX App',
    project: 'Onboarding App',
    owner: 'Marcelo',
    week: 'S5',
    bug: 'BUG-349',
  },
  {
    id: 'EN-1026',
    desc: 'Validação do checkout promocional',
    status: 'Finalizado',
    squad: 'B2B Digital',
    project: 'Campanha Flash',
    owner: 'Marcelo',
    week: 'S6',
    bug: '—',
  },
  {
    id: 'EN-1027',
    desc: 'Teste de elegibilidade por CEP',
    status: 'Impactado',
    squad: 'Core Fibra',
    project: 'Portal Comercial B2C',
    owner: 'Marcelo',
    week: 'S7',
    bug: 'BUG-360',
  },
]

export const mockBugs = [
  { id: 'BUG-342', desc: 'Timeout na consulta de elegibilidade', status: 'Em análise', owner: 'Backend', developer: 'George', squad: 'Core Fibra' },
  { id: 'BUG-349', desc: 'Divergência no resumo de pedido', status: 'Corrigido', owner: 'Frontend', developer: 'Aline', squad: 'CX App' },
  { id: 'BUG-355', desc: 'Erro ao atualizar pacote contratado', status: 'Crítico', owner: 'Integrações', developer: 'Rafael', squad: 'B2B Digital' },
  { id: 'BUG-359', desc: 'Tooltip sobreposto no mobile', status: 'Novo', owner: 'UX/UI', developer: 'Bianca', squad: 'CX App' },
  { id: 'BUG-360', desc: 'CEP inválido aceito em produção', status: 'Crítico', owner: 'Backend', developer: 'Lucas', squad: 'Core Fibra' },
]

export const mockLogs = [
  { id: 'LOG-1', message: 'Execução regressiva concluída no ambiente de homologação.', createdAt: '2026-04-15 09:00' },
  { id: 'LOG-2', message: 'Validação do fluxo de login finalizada sem desvios.', createdAt: '2026-04-15 10:10' },
  { id: 'LOG-3', message: 'Cenários de integração aguardando retorno da API parceira.', createdAt: '2026-04-15 13:40' },
  { id: 'LOG-4', message: 'Reteste do bug crítico programado para hoje às 17h.', createdAt: '2026-04-15 15:00' },
]
